GET http://localhost:3005/users
Content-Type: application/json

{
  "username": "kendrick",
  "password": "ekonash",
  "email": "kendrick@gmail.com",
  "firstname": "EkenKendrick"
}
###
GET http://localhost:3005/posts/user/5a4d662bd2b4933f34b601cd
Content-Type: application/json

{
  "author": "5a4d662bd2b4933f34b601cd",
  "title": "New Year Message",
  "body": "Happy new year people, hope you're all fine",
  "description": "No description yet"
}