GET http://localhost:3001/users/5a4d662bd2b4933f34b601cd
Content-Type: application/json

{
  "username": "ekonash",
  "password": "ekonash",
  "email": "ashinzekene@gmail.com",
  "firstname": "Ekene"
}