GET http://localhost:3001/users
Content-Type: application/json

{
  "username": "ekonash",
  "password": "ekonash",
  "email": "ashinzekene@gmail.com",
  "firstname": "Ekene"
}
###
GET http://localhost:3001/posts
